const countryCodes = [
    { code: '+1', name: 'USA/Canada' },
    { code: '+44', name: 'UK' },
    { code: '+353', name: 'Ireland' },
    { code: '+91', name: 'India' },
    { code: '+61', name: 'Australia' },
    { code: '+49', name: 'Germany' },
    { code: '+86', name: 'China' },
    { code: '+81', name: 'Japan' },
    { code: '+55', name: 'Brazil' },
    { code: '+33', name: 'France' },
    { code: '+39', name: 'Italy' },
    { code: '+34', name: 'Spain' },
    { code: '+7', name: 'Russia' },
    { code: '+27', name: 'South Africa' },
    { code: '+64', name: 'New Zealand' },
    { code: '+234', name: 'Nigeria' },
    { code: '+66', name: 'Thailand' },
    { code: '+971', name: 'United Arab Emirates' },
    { code: '+20', name: 'Egypt' },
    { code: '+212', name: 'Morocco' },
    { code: '+254', name: 'Kenya' },
    { code: '+351', name: 'Portugal' },
    { code: '+31', name: 'Netherlands' },
    { code: '+52', name: 'Mexico' },
    { code: '+82', name: 'South Korea' },
    { code: '+94', name: 'Sri Lanka' },
    { code: '+372', name: 'Estonia' },
    { code: '+48', name: 'Poland' },
    { code: '+358', name: 'Finland' },
    { code: '+46', name: 'Sweden' },
];

export default countryCodes;
