// This file contains common country codes to use in the phone number input
export const countryCodes = [
    { code: "+1", country: "US/CA" },
    { code: "+44", country: "UK" },
    { code: "+353", country: "IE" },
    { code: "+33", country: "FR" },
    { code: "+49", country: "DE" },
    { code: "+34", country: "ES" },
    { code: "+39", country: "IT" },
    { code: "+351", country: "PT" },
    { code: "+31", country: "NL" },
    { code: "+32", country: "BE" },
    { code: "+41", country: "CH" },
    { code: "+43", country: "AT" },
    { code: "+46", country: "SE" },
    { code: "+45", country: "DK" },
    { code: "+47", country: "NO" },
    { code: "+358", country: "FI" },
    { code: "+48", country: "PL" },
    { code: "+36", country: "HU" },
    { code: "+420", country: "CZ" },
    { code: "+30", country: "GR" },
    { code: "+61", country: "AU" },
    { code: "+64", country: "NZ" },
    { code: "+91", country: "IN" },
    { code: "+86", country: "CN" },
    { code: "+81", country: "JP" },
    { code: "+82", country: "KR" },
    { code: "+65", country: "SG" },
    { code: "+971", country: "AE" },
    { code: "+27", country: "ZA" },
    { code: "+55", country: "BR" },
    { code: "+52", country: "MX" },
];